copyright = "© 2024 DrowsyBao | 回"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Asia/Taipei"
timeout = "3600s"
title = "DrowsyBao | 回"

[sitemap]
  changefreq = 'weekly'
  disable = true
  priority = 0.8

[params]
  defaultTheme = "dark"
  title = "DrowsyBao | 回 Gallery"
  [params.author]
    email = "service@drowsybao.com"
    name = "Asa Kuo"
  [params.socialIcons]
    instagram = "https://www.instagram.com/drowsybao"
    blog = "https://drowsybao.com/blog/"
    email = "mailto:service@drowsybao.com"
    #facebook = "https://www.facebook.com/"
    #github = "https://github.com/AsaEwing/drowsybao-site"
    #youtube = "https://www.youtube.com/"
    #mastodon = "https://drowsybao.com"
    #pixelfed = "https://drowsybao.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 10
    identifier = "Blog"
  [[menus.main]]
    parent = 'Blog'
    name = '膠彩 血百合'
    pageRef = '/blog/膠彩_血百合'
    weight = 1
  [[menus.main]]
    parent = 'Blog'
    name = '膠彩 血百合'
    pageRef = '/blog/膠彩_星點秋海棠'
    weight = 1
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 10
  [[menus.main]]
    name = 'License'
    pageRef = '/license'
    weight = 10

[menu]
  [[menu.footer]]
    name = "License"
    url = "https://drowsybao.com/license"
    weight = 3

[services]
  [services.rss]
    limit = 100
