copyright = "© 2024 DrowsyBao"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Asia/Taipei"
timeout = "120s"
title = "DrowsyBao"

[params]
  defaultTheme = "dark"
  title = "DrowsyBao Gallery"
  [params.author]
    email = "service@drowsybao.com"
    name = "Asa Kuo"
  [params.socialIcons]
    instagram = "https://www.instagram.com/drowsybao"
    email = "mailto:service@drowsybao.com"
    #facebook = "https://www.facebook.com/"
    #github = "https://github.com/AsaEwing/drowsybao-site"
    #youtube = "https://www.youtube.com/"
    #website = "https://drowsybao.com"
    #mastodon = "https://drowsybao.com"
    #pixelfed = "https://drowsybao.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/tree/v4.1.12"

[menu]
  [[menu.footer]]
    name = "License"
    url = "https://drowsybao.com/license"
    weight = 3

[services]
  [services.rss]
    limit = 100
